### ISSUE TITLE
Jar files exported from eclipse is too huge

### ISSUE THREAD

**Issue by junghanChoi** [artclarke/humble-video#122]
I just wanted to use record function in the humble-video library.
I only added humble-video in the maven pom.xml.
The exported file is too huge. It's about 144 MB. 
Is there a way to build only I used classes?

**Comment by artclarke** [comment]
By default humble-video-all will include binaries for ALL operating systems (Windows 32 bit, Windows 64 bit, Linux 32 bit, Linux 64 bit, and MacOS 32 bit and 64 bit) because we can't tell which OS you're on. Humble has a lot of native (non-Java) code that needs to be compiled per operating system.

If you know you only need native bytes for a particular operating system, you can reduce your dependencies by depending on `humble-video-noarch` and then choosing the particular operating system versions you also need.

See the maven central locations for all the different operating system versions:
https://mvnrepository.com/artifact/io.humble
