### ISSUE TITLE
Exception being thrown in Muxer:  "Could not write header for url: [%s]. avdictionary"

### ISSUE THREAD

**Issue by kodjobaah** [artclarke/humble-video#19]
Hi Art,

I have been trying to get humble-video working in red5...But when I try to create a muxer it fails when trying to open it...the failure occurs when trying to write the header..
avformat_write_header

The snippet of code that is causing the error is below:

```
MuxerFormat muxerFormat = MuxerFormat.guessFormat("mpegts",null,null);
    log.info(muxerFormat.toString());
    Muxer container = Muxer.make(outputUrl, muxerFormat,"mpegts");

        KeyValueBag  meta = KeyValueBag.make();
        meta.setValue("service_provider", "Red5 HLS");
        meta.setValue("title", outputUrl.substring(outputUrl.indexOf(':') + 1));
        meta.setValue("map", "0");
        meta.setValue("segment_time", "" + facade.getSegmentTimeLimit() / 1000);
        meta.setValue("segment_format", "mpegts");
        meta.setValue("reset_timestamps", "0");
        container.open(meta, null);
```

Initially I thought it may have something to do with the header data...I made the following modifications to the Muxer.cpp this is why the error message looks a bit odd...

```
  AVDictionaryEntry *t = NULL;
  std::string out("");
  while ((t = av_dict_get(tmp, "", t, AV_DICT_IGNORE_SUFFIX))) {
out.append("key=");
out.append(t->key);
out.append("value=");
out.append(t->value);

  }
  out.append(url);
```

FfmpegException::check(retval, "Could not write header for url: [%s]. avdictionary: ", out.c_str());

This is the error thrown:
2014-03-03 12:31:33,222 [Thread-5] ERROR io.humble.video - HumbleInvalidArgument(finalStr): Could not write header for url: [key=service_providervalue=Red5 HLSkey=titlevalue=stream1393717419736key=mapvalue=0key=segment_timevalue=2key=segment_formatvalue=mpegtskey=reset_timestampsvalue=0redfivempegts:stream1393717419736]. avdictionary: Invalid argument (-22) (VideoExceptions.cpp:101)

when I compared the code in the muxer to this:
http://ffmpeg.org/doxygen/trunk/muxing_8c-source.html

I could not see where you was associating the videostream and audiostreams... is it not needed?

Another thing that is slightly confusing me..in the open method of the muxer...when you are checking for customio...not sure what the purpose of that is...

Any help would be greatly appreciated.

Kodjo

**Comment by mekya** [comment]
I would like to add one point to this thread. 

I am working on a simple hls plugin for red5. I have just encounter this issue. When I tried to create hls from mp4(encoded with libx264), it does not work. However ContainerSegmenterTest passes in the demos. After that, I realized that h264_mp4toannexb filter may increase the size of the packet. So that [vf.filter(packet, null)](https://github.com/artclarke/humble-video/blob/master/humble-video-demos/src/main/java/io/humble/video/demos/ContainerSegmenter.java#L119)
may return non-valid data. Because the required packet size is bigger than the current one. 

I hope this info may help some guys ;)
